language: generic
services:
  - docker
env:
  - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
before_install: |
  echo "Updating docker-compose to version 1.24.1" \
  && curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /tmp/docker-compose \
  && sudo rm /usr/local/bin/docker-compose \
  && sudo mv /tmp/docker-compose /usr/local/bin/docker-compose \
  && chmod +x /usr/local/bin/docker-compose \
  && cd $TRAVIS_BUILD_DIR \
  && git clone https://github.com/bbernhard/imagemonkey-core imagemonkey-core \
  && echo "Updating labels" \
  && mkdir -p $TRAVIS_BUILD_DIR/imagemonkey-core/wordlists \
  && cp -r $TRAVIS_BUILD_DIR/en $TRAVIS_BUILD_DIR/imagemonkey-core/wordlists/ \
  && cd $TRAVIS_BUILD_DIR/imagemonkey-core \
  && echo "Creating data directory" \
  && mkdir -p $TRAVIS_BUILD_DIR/imagemonkey-core/data/donations \
  && mkdir -p $TRAVIS_BUILD_DIR/imagemonkey-core/data/quarantine \
  && mkdir -p $TRAVIS_BUILD_DIR/imagemonkey-core/data/unverified_donations \
  && echo "Preparing env files for travis jobs" \
  && cp $TRAVIS_BUILD_DIR/imagemonkey-core/env/env.travis $TRAVIS_BUILD_DIR/imagemonkey-core/env/env_ui_tests.travis \
  && echo "TEST_MODE=only-ui" >> $TRAVIS_BUILD_DIR/imagemonkey-core/env/env_ui_tests.travis \
  && cp $TRAVIS_BUILD_DIR/imagemonkey-core/env/env.travis $TRAVIS_BUILD_DIR/imagemonkey-core/env/env_api_tests.travis \
  && echo "TEST_MODE=only-api" >> $TRAVIS_BUILD_DIR/imagemonkey-core/env/env_api_tests.travis \
  && cp $TRAVIS_BUILD_DIR/imagemonkey-core/env/env.travis $TRAVIS_BUILD_DIR/imagemonkey-core/env/env_unit_tests.travis \
  && echo "TEST_MODE=only-unittest" >> $TRAVIS_BUILD_DIR/imagemonkey-core/env/env_unit_tests.travis \
  && docker-compose -f env/docker/docker-compose-labels-test.travis.yml pull

jobs:
  include:
    - stage: test
      script: cd $TRAVIS_BUILD_DIR/imagemonkey-core && docker-compose -f env/docker/docker-compose-labels-test.travis.yml up --abort-on-container-exit --exit-code-from testing
      env:
        - ENV_FILE_LOCATION=../env_api_tests.travis
    - # stage name not required, will continue to use `test`
      script: cd $TRAVIS_BUILD_DIR/imagemonkey-core && docker-compose -f env/docker/docker-compose-labels-test.travis.yml up --abort-on-container-exit --exit-code-from testing
      env:  
        - ENV_FILE_LOCATION=../env_unit_tests.travis
